### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by md2perpe** [wwalexander/go-bencode#1]
Since Go has a binary format [gob](https://golang.org/pkg/encoding/gob/) the name of this repository is easily read as "gob-encode" instead of "go-bencode".

I would therefore suggest a rename to "go-bencode".

Renaming can be found under [Settings](https://github.com/wwalexander/gobencode/settings).

**Comment by wwalexander** [comment]
Good point. I wanted to stay idiomatic (gofmt, golint, etc) but this is very misleading. I've renamed the repository.
